app:
  file-resource:
    prefix: file_resource

server:
  port: 9001
  session:
    cookie:
      secure: true

spring:
  application:
    name: blacksky

  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test?useAffectedRows=true
    username: root
    password: test

  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB

mybatis:
  mapper-locations: classpath:db/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com.albertflex.blacksky.mapper: trace
    org.springframework.security: debug
